In [14]:
import roboticstoolbox as rtb
import numpy as np
import torch

from experim0 import Regressor
from experimRobo import denorm_q
""""""
# args
""""""
lr = 1e-3
depth = 10
mid_layer_size = 10
activation = torch.relu
batch_size = 512
epochs = 500

robot = rtb.models.DH.Cobra600()

input_dim = robot.n
output_dim = 3
""""""

path = 'models/experimRobo/v1.pt'
model = Regressor(input_dim, output_dim,
                    depth, mid_layer_size,
                    activation)
model.load_state_dict(torch.load(path))
model.eval()

q_test = np.array([0.5, 0.6, 0.2, 0.9])
real = robot.fkine(denorm_q(robot, q_test)).t
pred = model(torch.tensor(q_test).float()).detach()

robot.qlim, real, pred

(array([[-0.87266463, -1.53588974,  0.        , -3.14159265],
        [ 0.87266463,  1.53588974,  0.21      ,  3.14159265]]),
 array([0.58712743, 0.08315172, 0.345     ]),
 tensor([0.5360, 0.0635, 0.3493]))

In [42]:
samples = np.zeros((8, robot.n))#np.random.rand(8, robot.n)
qlims = robot.qlim
q_min, q_max = qlims

np.concatenate((qlims.T, 12*np.ones((robot.n,1))), axis=1) #, samples * (q_max-q_min) + q_min

array([[-0.87266463,  0.87266463, 12.        ],
       [-1.53588974,  1.53588974, 12.        ],
       [ 0.        ,  0.21      , 12.        ],
       [-3.14159265,  3.14159265, 12.        ]])

In [11]:
import numpy as np

np.stack(np.meshgrid([1, 2, 3], [4, 5], [6, 7]), -1).reshape(-1, 3)

array([[1, 4, 6],
       [1, 4, 7],
       [2, 4, 6],
       [2, 4, 7],
       [3, 4, 6],
       [3, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 5, 6],
       [3, 5, 7]])

In [4]:
import numpy as np

a = np.arange(10)
b = np.arange(10)
np.einsum('i->i',a)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0