In [20]:
def f(a=10,b=10):
    return a+b
def g(**kwags):
    return a+b
arg = {'a':1, 'b':2} #, 'c':3}
f(**arg)

3

In [1]:
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--a', type=int)
parser.add_argument('--b', type=int)
parser.add_argument('--c', type=int)
args = parser.parse_args(['--a', '1', '--b', '2', '--c', '3'])

In [4]:
import roboticstoolbox as rtb
import numpy as np
import torch

robot = rtb.models.DH.Puma560()
robot.fkine(np.zeros(robot.n)).t

array([ 0.4521 , -0.15005,  1.10363])

In [ ]:
import numpy as np 
np.meshgrid()

In [3]:
n_samples = 5
input_dim = 2
def f(x):
    r = torch.linalg.norm(4*x**2, dim=1)
    return torch.sin(r).view(-1,1)
x = torch.rand(n_samples, input_dim)
y = f(x)
x, y

(tensor([[0.6346, 0.4112],
         [0.9095, 0.4123],
         [0.3029, 0.7260],
         [0.1700, 0.9012],
         [0.1265, 0.8438]]),
 tensor([[ 0.9845],
         [-0.2342],
         [ 0.8424],
         [-0.1087],
         [ 0.2889]]))

In [5]:
import torch
import numpy as np
x1 = np.linspace((0,5), (5,8), 10)
x2 = torch.linspace(0, 5, 5).view(-1, 1)

x1, x2#, torch.meshgrid([x1, x2])

(array([[0.        , 5.        ],
        [0.55555556, 5.33333333],
        [1.11111111, 5.66666667],
        [1.66666667, 6.        ],
        [2.22222222, 6.33333333],
        [2.77777778, 6.66666667],
        [3.33333333, 7.        ],
        [3.88888889, 7.33333333],
        [4.44444444, 7.66666667],
        [5.        , 8.        ]]),
 tensor([[0.0000],
         [1.2500],
         [2.5000],
         [3.7500],
         [5.0000]]))

In [5]:
import torch

def f(x): return x.sum(axis=1).view(-1,1)

x1_plot = torch.linspace(0, 2, 3)
x2_plot = torch.linspace(5, 7, 3)

x1_grid, x2_grid = torch.meshgrid(x1_plot, x2_plot)

stack = torch.stack([x1_grid, x2_grid], dim=1)

x1_grid, x2_grid, torch.stack([x1_grid, x2_grid], dim=-1).view(-1,2)

(tensor([[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.]]),
 tensor([[5., 6., 7.],
         [5., 6., 7.],
         [5., 6., 7.]]),
 tensor([[0., 5.],
         [0., 6.],
         [0., 7.],
         [1., 5.],
         [1., 6.],
         [1., 7.],
         [2., 5.],
         [2., 6.],
         [2., 7.]]))