In [4]:
import torch

In [5]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[0,1],[1,0]])
a.size(0)

#a, b

2

In [6]:
torch.einsum('ij->ji', a)
torch.transpose(a,-1,-2)

tensor([[1, 3],
        [2, 4]])

In [7]:
a.storage()

 1
 2
 3
 4
[torch.LongStorage of size 4]

In [8]:
#Codificación de puntajes en formato one-hot
scores = torch.tensor([[4, 8, 9, 4, 5, 7, 9, 7, 6, 6, 7]])
scores.transpose_(0, 1)
scores_onehot = torch.zeros(scores.shape[0], 10)
scores_onehot.scatter_(1, scores, 1.0)

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [9]:
# El autograd acumula los gradientes en el atributo grad de cada parámetro. Los gradientes se siguen acumulando hasta que se reinicia manualmente.
import torch

a = torch.tensor([1., 0.], requires_grad=True)
b = torch.tensor([0., 1.], requires_grad=True)

g = a**2 + 3*b
g.backward(gradient = torch.tensor([1.,1.]))
print(2*a == a.grad)
print(3 == b.grad)
a, b, a.grad, b.grad, g

tensor([True, True])
tensor([True, True])


(tensor([1., 0.], requires_grad=True),
 tensor([0., 1.], requires_grad=True),
 tensor([2., 0.]),
 tensor([3., 3.]),
 tensor([1., 3.], grad_fn=<AddBackward0>))

In [ ]:
a = torch.tensor([1., 0.])
b = torch.tensor([0., 1.]).unsqueeze_(1)

f = lambda x : torch.sin(3*x) + x**2

f(a), f(b)

(tensor([1.1411, 0.0000]),
 tensor([[0.0000],
         [1.1411]]))

In [ ]:
a = torch.tensor([1., 0., 2., 3.1, 0.1, 0.2, 2.1])
b = torch.stack([a, 2*a, 0.5*a]).squeeze(0)
print(a<2)
print(b<2)
print(sum(a<2))
print(torch.sum(b<2))

tensor([ True,  True, False, False,  True,  True, False])
tensor([[ True,  True, False, False,  True,  True, False],
        [False,  True, False, False,  True,  True, False],
        [ True,  True,  True,  True,  True,  True,  True]])
tensor(4)
tensor(14)


In [17]:
def testgen(x):
    i = 0
    while i < x:
        yield i
        i+=1

torch.tensor(testgen(3), dtype = torch.float32)

range(0, 3)

In [18]:
torch.arange(5).unsqueeze(1)

tensor([[0],
        [1],
        [2],
        [3],
        [4]])